### ISSUE TITLE
use datepicker Uncaught TypeError?

### ISSUE THREAD

**Issue by seagod** [emberjs-addons/ember-bootstrap#85]
Uncaught TypeError: Object [object Object] has no method 'datepicker' ember-bootstrap.min.js:546

{{view App.Bootstrap.DatePicker valueBinding="taskStartTime"}}

why it's not work?

**Comment by dmathieu** [comment]
Once again, you're definitely not using this Ember Bootstrap.
There is no DatePicker in this library (and there won't be unless the Bootstrap includes one in it's core library).

As for the future: you can tell this not this ember bootstrap because we're namespacing with only `Bootstrap`. You're namespacing with `App.Bootstrap`.
